/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.form;

import com.Dao.CaLamDao;
import com.Dao.TongKetCaLamDao;
import com.untils.XDialog;
import com.untils.getJOptionePane;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAccessor;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class GiaoCa extends javax.swing.JDialog {

    TongKetCaLamDao dao = new TongKetCaLamDao();
    List<Object[]> lsCa = new ArrayList<>();
    CaLamDao clDao = new CaLamDao();
    String thuHienTai = "";
    String caLamHienTai = "";
    String gioBD = "";
    String gioKT = "";
    String NgayHomNay = "";
    double TienTrongKet = 3000000;
    String user = "Nguyen Van A";
    String maNV = "NV001";
    String GetDay = "";
    String GetToDay = "";

    /**
     * Creates new form GiaoCa
     */
    public GiaoCa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        updateThongTin();
        init();
        try {
            jDateChooser2.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
                @Override
                public void propertyChange(PropertyChangeEvent e) {
                    if ("date".equals(e.getPropertyName())) {
                        // Xử lý khi ngày thay đổi ở đây
                        Date selectedDate = (Date) e.getNewValue();
                        // Thực hiện các thao tác cần thiết khi ngày thay đổi
                        SimpleDateFormat formatter = new SimpleDateFormat("yyyy/dd/MM");
                        GetDay = formatter.format(jDateChooser2.getDate());
                        fillTableLSCaByDate(GetDay);
                    }
                }
            });
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTenCa = new javax.swing.JLabel();
        lblTenThuNgan = new javax.swing.JLabel();
        lblTienKet = new javax.swing.JLabel();
        lblTongTienHDC = new javax.swing.JLabel();
        lblSoLuongHDC = new javax.swing.JLabel();
        lblTongTienHD = new javax.swing.JLabel();
        lblSoLuongHD = new javax.swing.JLabel();
        lblTienMat = new javax.swing.JLabel();
        lblChuyenKhoan = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        btnGiaoCa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLichSuCa = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnTatCa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(244, 154, 157));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setText("Tổng kết ca làm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 310, 50));

        jTabbedPane1.setBackground(new java.awt.Color(244, 154, 157));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(244, 154, 157));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên ca:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên thu ngân:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Số lượng hóa đơn:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tổng tiền hóa đơn:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Số lượng hóa đơn chi:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tổng tiền hóa đơn chi:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tổng tiền chuyển khoản:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tổng tiền mặt:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 51));
        jLabel11.setText("Doanh thu:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tiền trong két:");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        lblTenCa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenCa.setText("-----");

        lblTenThuNgan.setText("-----");

        lblTienKet.setText("-----");

        lblTongTienHDC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTienHDC.setText("----");

        lblSoLuongHDC.setText("-----");

        lblTongTienHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTongTienHD.setText("-----");

        lblSoLuongHD.setText("-----");

        lblTienMat.setText("------");

        lblChuyenKhoan.setText("-----");

        lblDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDoanhThu.setForeground(new java.awt.Color(153, 0, 51));
        lblDoanhThu.setText("----");

        btnGiaoCa.setBackground(new java.awt.Color(175, 42, 46));
        btnGiaoCa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGiaoCa.setForeground(new java.awt.Color(255, 255, 255));
        btnGiaoCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8-assign-25.png"))); // NOI18N
        btnGiaoCa.setText("Giao ca");
        btnGiaoCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaoCaActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(41, 157, 175));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/Exit.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tblNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Tên nhân viên", "Trạng thái", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setSelectionBackground(new java.awt.Color(244, 100, 104));
        jScrollPane2.setViewportView(tblNhanVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTenCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTenThuNgan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTienKet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblChuyenKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTongTienHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTienMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSoLuongHDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSoLuongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTongTienHDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnGiaoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTenCa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTenThuNgan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblTienKet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTongTienHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblSoLuongHD))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTongTienHDC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuongHDC)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblTienMat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblChuyenKhoan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblDoanhThu))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGiaoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Tổng ca", jPanel2);

        jPanel3.setBackground(new java.awt.Color(244, 154, 157));

        tblLichSuCa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblLichSuCa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã ca", "Tên ca", "Tên thu ngân", "Tổng tiền hóa đơn", "Tiền hóa đơn chi", "Doanh thu"
            }
        ));
        tblLichSuCa.setSelectionBackground(new java.awt.Color(244, 100, 104));
        jScrollPane1.setViewportView(tblLichSuCa);

        jButton1.setBackground(new java.awt.Color(41, 148, 175));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Hôm nay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnTatCa.setBackground(new java.awt.Color(175, 42, 46));
        btnTatCa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTatCa.setForeground(new java.awt.Color(255, 255, 255));
        btnTatCa.setText("Tất cả");
        btnTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTatCaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Chọn ngày:");

        jDateChooser2.setDateFormatString("yyyy/dd/MM");
        jDateChooser2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDateChooser2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jDateChooser2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooser2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lịch sử", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void btnTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTatCaActionPerformed
        fillTableLSCa();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTatCaActionPerformed

    public void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    public void btnGiaoCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaoCaActionPerformed
        ThemGiaoCa();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGiaoCaActionPerformed

    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fillTableLSCaByDate(NgayHomNay);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void jDateChooser2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser2KeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2KeyReleased

    public void jDateChooser2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser2AncestorAdded

// TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaoCa dialog = new GiaoCa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGiaoCa;
    public javax.swing.JButton btnTatCa;
    public javax.swing.JButton btnThoat;
    public javax.swing.JButton jButton1;
    public com.toedter.calendar.JDateChooser jDateChooser2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lblChuyenKhoan;
    public javax.swing.JLabel lblDoanhThu;
    public javax.swing.JLabel lblSoLuongHD;
    public javax.swing.JLabel lblSoLuongHDC;
    public javax.swing.JLabel lblTenCa;
    public javax.swing.JLabel lblTenThuNgan;
    public javax.swing.JLabel lblTienKet;
    public javax.swing.JLabel lblTienMat;
    public javax.swing.JLabel lblTongTienHD;
    public javax.swing.JLabel lblTongTienHDC;
    public javax.swing.JTable tblLichSuCa;
    public javax.swing.JTable tblNhanVien;
    // End of variables declaration//GEN-END:variables
public void init() {
        fillDataCalam();
        fillTableNhanVien();
        fillTableLSCa();
    }

    public void fillDataCalam() {
        if (caLamHienTai.equalsIgnoreCase("Ca Tối")) {
            gioBD = "00:00:00";
        } else if (caLamHienTai.equalsIgnoreCase("Ca Sáng")) {
            gioBD = "06:00:00";
        } else if (caLamHienTai.equalsIgnoreCase("Ca Trưa")) {
            gioBD = "12:00:00";
        } else {
            gioBD = "18:00:00";
        }
        List<Object[]> list = dao.getDataGiaoCa(gioBD, gioKT);
        if (list.size() != 0) {
            Object[] Col = list.get(0); // Lấy hàng đầu tiên từ danh sách
            lblTenCa.setText(caLamHienTai);
            lblTenThuNgan.setText(user);
            lblTienKet.setText(String.valueOf(TienTrongKet));
            double tongtienHD = (Double) Col[0];
            lblTongTienHD.setText(String.valueOf(tongtienHD));
            int SLHD = (Integer) Col[1];
            lblSoLuongHD.setText(String.valueOf(SLHD));
            double TongTienHDC = 0;
            if (Col[2] != null) {
                TongTienHDC = (Double) Col[2];
            }
            lblTongTienHDC.setText(String.valueOf(TongTienHDC));
            int SLHDC = (Integer) Col[3];
            lblSoLuongHDC.setText(String.valueOf(SLHDC));
            double TongTienMat = (Double) Col[4];
            lblTienMat.setText(String.valueOf(TongTienMat));
            double TongTienCK = 0;
            if (Col[5] != null) {
                TongTienCK = (Double) Col[5];
            }

            lblChuyenKhoan.setText(String.valueOf(TongTienCK));
            double doanhThu = 0;
            if (Col[6] != null) {
                doanhThu = (Double) Col[6];
            }

            lblDoanhThu.setText(String.valueOf(doanhThu));

        } else {
            lblTenCa.setText(caLamHienTai);
            lblTenThuNgan.setText(user);
            lblTienKet.setText(String.valueOf(TienTrongKet));
            lblTongTienHD.setText("0");
            lblSoLuongHD.setText("0");
            lblTongTienHDC.setText("0");
            lblSoLuongHDC.setText("0");
            lblTienMat.setText("0");
            lblChuyenKhoan.setText("0");
            lblDoanhThu.setText("0");
        }

    }

    public void fillTableNhanVien() {
        DefaultTableModel model1 = (DefaultTableModel) tblNhanVien.getModel();
        model1.setRowCount(0);
        int i = 0;
        boolean trangthai = false;
        List<Object[]> list = clDao.getNhanVienTrongCa(caLamHienTai, thuHienTai);
        for (Object[] row : list) {
            i++;
            if (String.valueOf(row[1]).equalsIgnoreCase("Vắng mặt")) {
                trangthai = false;
            } else {
                trangthai = true;
            }
            model1.addRow(new Object[]{i, row[0], trangthai, row[2]});
        }
    }

    public void fillTableLSCa() {
        DefaultTableModel model = (DefaultTableModel) tblLichSuCa.getModel();
        model.setRowCount(0);
        try {
            List<Object[]> list = dao.SelectALl();
            for (Object[] row : list) {
                model.addRow(new Object[]{row[0], row[1], row[2], row[3], row[4], row[5]});
                lsCa.add(new Object[]{row[0], row[1], row[2], row[3], row[4], row[5], row[6]});
            }
        } catch (Exception e) {
              getJOptionePane.methodThatUsesOptionPane(this, "Lỗi truy vấn dữ lịch sử giao ca!");
            e.printStackTrace();
        }
    }

    public void fillTableLSCaByDate(String day) {
        DefaultTableModel model = (DefaultTableModel) tblLichSuCa.getModel();
        model.setRowCount(0);
        try {
            List<Object[]> list = dao.SelectByDate(day);
            for (Object[] row : list) {
                model.addRow(new Object[]{row[0], row[1], row[2], row[3], row[4], row[5]});
            }
        } catch (Exception e) {
            // XDialog.alert(this, "Lỗi truy vấn dữ lịch sử giao ca!");
            //  e.printStackTrace();
        }
    }

    public String xacDinhCaLam(int gio) {
        if (gio >= 0 && gio < 6) {
            return "Ca Tối";
        } else if (gio >= 6 && gio < 12) {
            return "Ca Sáng";
        } else if (gio >= 12 && gio < 18) {
            return "Ca Trưa";
        } else {
            return "Ca Chiều";
        }
    }

    public void updateThongTin() {
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        DateTimeFormatter formatter1 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("yyyy/dd/MM");
        String gioHienTai = now.format(formatter);
        String homNay = now.format(formatter1);
        String homNay1 = now.format(formatter2);
        formatter = DateTimeFormatter.ofPattern("EEEE", new Locale("vi")); // "EEEE" để lấy tên thứ
        thuHienTai = now.format(formatter);
        caLamHienTai = xacDinhCaLam(now.getHour());
        gioKT = gioHienTai;
        NgayHomNay = homNay;
        GetToDay = homNay1;
    }

    public void ThemGiaoCa() {

        List<Object[]> nv = new ArrayList<>();
        boolean check = true;
        nv.add(new Object[]{maNV, lblTenCa.getText(), lblSoLuongHD.getText(), lblTongTienHD.getText(), lblSoLuongHDC.getText(), lblTongTienHDC.getText(), lblChuyenKhoan.getText(), lblTienMat.getText(), lblDoanhThu.getText(), NgayHomNay});
        if (!lsCa.isEmpty()) {
            for (Object[] lsc : lsCa) {
                Timestamp timestamp = (Timestamp) lsc[6];
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                String dateinList = dateFormat.format(timestamp);
                String cainList = (String) lsc[1];

                if (cainList.equalsIgnoreCase(caLamHienTai) && dateinList.equalsIgnoreCase(GetToDay)) {
                    check = true;
//                    System.out.println("Check = true");
//                    System.out.println("CaInList: " + cainList);
//                    System.out.println("caHienTai: " + caLamHienTai);
//                    System.out.println("Dateinlist: " + dateinList);
//                    System.out.println("GettoDay: " + GetToDay);

                } else {
                    check = false;
//                    System.out.println("Check = false");
//                    System.out.println("CaInList: " + cainList);
//                    System.out.println("CaHienTai: " + caLamHienTai);
//                    System.out.println("Dateinlist: " + dateinList);
//                    System.out.println("GettoDay: " + GetToDay);
                }
            }
        } else {
            dao.updateDatabase(maNV, lblTenCa.getText(), Integer.parseInt(lblSoLuongHD.getText()), Double.parseDouble(lblTongTienHD.getText()), Integer.parseInt(lblSoLuongHDC.getText()), Double.parseDouble(lblTongTienHDC.getText()), Double.parseDouble(lblChuyenKhoan.getText()), Double.parseDouble(lblTienMat.getText()), Double.parseDouble(lblDoanhThu.getText()), String.valueOf(NgayHomNay));
              getJOptionePane.methodThatUsesOptionPane(this, "Đã lưu ca hôm nay ");
            fillTableLSCa();
              getJOptionePane.methodThatUsesOptionPane(null, "Giao ca thành công!");
            return;
        }

        if (check == true) {
            dao.updateDatabaseTontai(Integer.parseInt(lblSoLuongHD.getText()), Double.parseDouble(lblTongTienHD.getText()), Integer.parseInt(lblSoLuongHDC.getText()), Double.parseDouble(lblTongTienHDC.getText()), Double.parseDouble(lblChuyenKhoan.getText()), Double.parseDouble(lblTienMat.getText()), Double.parseDouble(lblDoanhThu.getText()));
              getJOptionePane.methodThatUsesOptionPane(this, "Đã cập nhật ca hôm nay");
        } else {
            dao.updateDatabase(maNV, lblTenCa.getText(), Integer.parseInt(lblSoLuongHD.getText()), Double.parseDouble(lblTongTienHD.getText()), Integer.parseInt(lblSoLuongHDC.getText()), Double.parseDouble(lblTongTienHDC.getText()), Double.parseDouble(lblChuyenKhoan.getText()), Double.parseDouble(lblTienMat.getText()), Double.parseDouble(lblDoanhThu.getText()), String.valueOf(NgayHomNay));
              getJOptionePane.methodThatUsesOptionPane(this, "Đã lưu ca hôm nay ");
        }

        fillTableLSCa();
          getJOptionePane.methodThatUsesOptionPane(null, "Giao ca thành công!");
    }

}
