/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.form;

import com.Dao.HoaDonDAO_1;
import com.model.HoaDon;
import com.untils.XAuth;
import com.untils.XDate;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author HP
 */
public class HoaDon2 extends javax.swing.JPanel {

    HoaDonDAO_1 hdDao = new HoaDonDAO_1();
    int row = -1;
    int row1 = -1;
    String userInput;
    List<String> statuses = new ArrayList<>();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

    /**
     * Creates new form HoaDon2
     */
    public HoaDon2() {
        initComponents();
        init();

        jdcNgay.addPropertyChangeListener("date", e -> {
            if ("date".equals(e.getPropertyName())) {
                String ngayChon = String.valueOf(dateFormat.format(jdcNgay.getDate()));
                fillHDTheoNgay(ngayChon);
                Reset2();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonCT = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblMaHD = new javax.swing.JLabel();
        lblNguoiTao = new javax.swing.JLabel();
        lblKhuyenMai = new javax.swing.JLabel();
        lblThoiGianThanhToan = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        lblTienSP = new javax.swing.JLabel();
        lblPhiKhac = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblThoiGianTao = new javax.swing.JLabel();
        lblHuy = new javax.swing.JLabel();
        lblNoiDungHuy = new javax.swing.JLabel();
        btnXacNhanHuy = new javax.swing.JButton();
        btnTuChoiHuy = new javax.swing.JButton();
        lblVoucher = new javax.swing.JLabel();
        lblGiaTriVouCher = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLSHoaDon = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblMaHD1 = new javax.swing.JLabel();
        lblNguoiTao1 = new javax.swing.JLabel();
        lblThoiGianTao1 = new javax.swing.JLabel();
        lblThoiGianTT1 = new javax.swing.JLabel();
        lblGhiChu1 = new javax.swing.JLabel();
        lblTrangThai1 = new javax.swing.JLabel();
        lblTienSP1 = new javax.swing.JLabel();
        lblPhiKhac1 = new javax.swing.JLabel();
        lblTongTien1 = new javax.swing.JLabel();
        lblLyDo = new javax.swing.JLabel();
        lbllLyDoHuy = new javax.swing.JLabel();
        jdcNgay = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        lblGiaTriVoucher1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 154, 157));
        setPreferredSize(new java.awt.Dimension(959, 615));

        jPanel1.setBackground(new java.awt.Color(244, 154, 157));

        jTabbedPane1.setBackground(new java.awt.Color(244, 154, 157));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(244, 154, 157));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(244, 154, 157));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("HÓA ĐƠN");

        jButton1.setBackground(new java.awt.Color(175, 42, 46));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/Accept.png"))); // NOI18N
        jButton1.setText("Xác Nhận Hóa Đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã HĐ", "Người Tạo", "Thời Gian Tạo", "Tổng Tiền", "Ghi Chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tblHoaDon.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDon);

        jButton2.setBackground(new java.awt.Color(175, 42, 46));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8-cancel-25.png"))); // NOI18N
        jButton2.setText("Hủy Hóa Đơn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("+Hóa đơn yêu cầu hủy");

        jLabel22.setText("+Hóa đơn chờ xác nhận");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel22)
                    .addContainerGap(133, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel22)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(47, 47, 47))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 680));

        jPanel4.setBackground(new java.awt.Color(244, 154, 157));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("HÓA ĐƠN CHI TIẾT");

        tblHoaDonCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblHoaDonCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên SP", "Đơn Giá", "Số Lượng", "Thành Tiền", "Ghi Chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonCT.setSelectionBackground(new java.awt.Color(244, 126, 130));
        jScrollPane1.setViewportView(tblHoaDonCT);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("THÔNG TIN CHI TIẾT");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã hóa đơn:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Người tạo:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Thời gian tạo:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Thời gian TT:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Ghi chú:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Trạng thái:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Tiền SP:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Phi khác:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Tổng tiền:");

        lblMaHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNguoiTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblThoiGianThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTienSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPhiKhac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblThoiGianTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHuy.setText("Lý do hủy:");

        lblNoiDungHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNoiDungHuy.setText("-----");

        btnXacNhanHuy.setBackground(new java.awt.Color(175, 42, 46));
        btnXacNhanHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXacNhanHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhanHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/Accept.png"))); // NOI18N
        btnXacNhanHuy.setText("Xác Nhận Hủy");
        btnXacNhanHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanHuyActionPerformed(evt);
            }
        });

        btnTuChoiHuy.setBackground(new java.awt.Color(175, 42, 46));
        btnTuChoiHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTuChoiHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnTuChoiHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8-cancel-25.png"))); // NOI18N
        btnTuChoiHuy.setText("Từ Chối Hủy");
        btnTuChoiHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuChoiHuyActionPerformed(evt);
            }
        });

        lblVoucher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVoucher.setText("Voucher:");

        lblGiaTriVouCher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(122, 122, 122))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblThoiGianThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblThoiGianTao, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTienSP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPhiKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblVoucher)
                                        .addGap(1, 1, 1)
                                        .addComponent(lblGiaTriVouCher, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblHuy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNoiDungHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnTuChoiHuy)
                        .addGap(32, 32, 32)
                        .addComponent(btnXacNhanHuy)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblNguoiTao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKhuyenMai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblThoiGianTao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblThoiGianThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblTienSP, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblPhiKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVoucher)
                        .addComponent(lblGiaTriVouCher, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHuy)
                    .addComponent(lblNoiDungHuy))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTuChoiHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhanHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 550, 680));

        jTabbedPane1.addTab("Hóa Đơn Chờ", jPanel2);

        jPanel5.setBackground(new java.awt.Color(244, 154, 157));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("LỊCH SỬ HÓA ĐƠN");

        tblLSHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblLSHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã HĐ", "Người Tạo", "Thời Gian Tạo", "Thời Gian Thanh Toán", "Tổng Tiền", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLSHoaDon.setSelectionBackground(new java.awt.Color(244, 126, 130));
        tblLSHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLSHoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLSHoaDon);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Trạng thái:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Chi Phí Khác:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("Tiền SP:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("Tổng tiền:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setText("THÔNG TIN CHI TIẾT");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText("Mã hóa đơn:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("Người tạo:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setText("Thời gian tạo:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setText("Thời gian thanh toán:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setText("Ghi chú:");

        lblMaHD1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaHD1.setText("---");

        lblNguoiTao1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNguoiTao1.setText("---");

        lblThoiGianTao1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThoiGianTao1.setText("---");

        lblThoiGianTT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThoiGianTT1.setText("---");

        lblGhiChu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGhiChu1.setText("---");

        lblTrangThai1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTrangThai1.setText("----");

        lblTienSP1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTienSP1.setText("---");

        lblPhiKhac1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhiKhac1.setText("---");

        lblTongTien1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTongTien1.setText("---");

        lblLyDo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLyDo.setText("Lý do hủy:");

        lbllLyDoHuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbllLyDoHuy.setText("---");

        jdcNgay.setDateFormatString("dd/MM/yyyy");
        jdcNgay.setOpaque(false);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setText("Voucher:");

        lblGiaTriVoucher1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGiaTriVoucher1.setText("---");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jdcNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblLyDo)
                                .addGap(18, 18, 18)
                                .addComponent(lbllLyDoHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTrangThai1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblPhiKhac1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel17)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jLabel19))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMaHD1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(8, 8, 8)
                                        .addComponent(lblNguoiTao1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(3, 3, 3)
                                        .addComponent(lblThoiGianTao1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(250, 250, 250)
                                        .addComponent(lblThoiGianTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel24)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblGiaTriVoucher1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(148, 148, 148)
                                .addComponent(lblTienSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jdcNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(lblMaHD1))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblNguoiTao1)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblThoiGianTao1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblThoiGianTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(lblGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(lblTienSP1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(lblTrangThai1))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblPhiKhac1)))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel17)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(lblTongTien1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLyDo)
                            .addComponent(lbllLyDoHuy))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiaTriVoucher1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lịch Sử", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        row = tblHoaDon.getSelectedRow();
        String maHD = (String) tblHoaDon.getValueAt(row, 0);
        fillTableHoaDonCT();
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateHoaDon();
        Reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblLSHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLSHoaDonMouseClicked
        try {
            row1 = tblLSHoaDon.getSelectedRow();
            String maHD = (String) tblLSHoaDon.getValueAt(row1, 0);
            fillTableLSHoaDonCT();
            xemLyDo();
        } catch (Exception e) {
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tblLSHoaDonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        userInput = JOptionPane.showInputDialog("Lý do hủy:");
        if (userInput != null) {
            updateHuyHoaDon();

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnXacNhanHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanHuyActionPerformed
        updateXacNhanHuy();
    }//GEN-LAST:event_btnXacNhanHuyActionPerformed

    private void btnTuChoiHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuChoiHuyActionPerformed
        updateTrangThaiHuy();
    }//GEN-LAST:event_btnTuChoiHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTuChoiHuy;
    private javax.swing.JButton btnXacNhanHuy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdcNgay;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGhiChu1;
    private javax.swing.JLabel lblGiaTriVouCher;
    private javax.swing.JLabel lblGiaTriVoucher1;
    private javax.swing.JLabel lblHuy;
    private javax.swing.JLabel lblKhuyenMai;
    private javax.swing.JLabel lblLyDo;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblMaHD1;
    private javax.swing.JLabel lblNguoiTao;
    private javax.swing.JLabel lblNguoiTao1;
    private javax.swing.JLabel lblNoiDungHuy;
    private javax.swing.JLabel lblPhiKhac;
    private javax.swing.JLabel lblPhiKhac1;
    private javax.swing.JLabel lblThoiGianTT1;
    private javax.swing.JLabel lblThoiGianTao;
    private javax.swing.JLabel lblThoiGianTao1;
    private javax.swing.JLabel lblThoiGianThanhToan;
    private javax.swing.JLabel lblTienSP;
    private javax.swing.JLabel lblTienSP1;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTongTien1;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblTrangThai1;
    private javax.swing.JLabel lblVoucher;
    private javax.swing.JLabel lbllLyDoHuy;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblHoaDonCT;
    private javax.swing.JTable tblLSHoaDon;
    // End of variables declaration//GEN-END:variables
public void init() {
        fillTableHoaDon();
        fillTableHoaDonCT();
        fillTableLSHoaDon();
        lblLyDo.setVisible(false);
        lbllLyDoHuy.setVisible(false);
        lblHuy.setVisible(false);
        lblNoiDungHuy.setVisible(false);
        btnXacNhanHuy.setVisible(false);
        btnTuChoiHuy.setVisible(false);
// 
        Date d = new Date();
        jdcNgay.setDate(d);
//        tblHoaDon.setDefaultRenderer(Object.class, new CustomRowRenderer(statuses));
    }

    public void fillTableHoaDon() {

        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();

        model.setRowCount(0);
        statuses.clear();
        List<Object[]> list = hdDao.getHoaDon();
        for (Object[] row : list) {
            statuses.add((String) row[8]);
            //Thay đổi Row[2] thành Row[10] 
            model.addRow(new Object[]{row[0], row[9], row[1], String.format("%,.0f", row[4]), row[7]});
        }
        tblHoaDon.setDefaultRenderer(Object.class, new CustomRowRenderer(statuses));
        // Áp dụng renderer cho từng cột

    }

    public void fillTableLSHoaDon() {
        DefaultTableModel model = (DefaultTableModel) tblLSHoaDon.getModel();
        model.setRowCount(0);
        List<Object[]> list = hdDao.getLSHoaDon();
        for (Object[] row : list) {
            model.addRow(new Object[]{row[0], row[1], row[2], row[3],String.format("%,.0f", row[4]), row[5]});
        }
    }

    public void fillTableHoaDonCT() {
        String maHD = "";
        DefaultTableModel model = (DefaultTableModel) tblHoaDonCT.getModel();
        model.setRowCount(0);
        try {
            maHD = (String) tblHoaDon.getValueAt(row, 0);
        } catch (Exception e) {
        }

        List<Object[]> list = hdDao.getHoaDonCT(maHD);
        for (Object[] row : list) {
            model.addRow(new Object[]{row[0], row[1], row[2], String.format("%,.0f", row[3]), row[4]});
        }
        lblMaHD.setText(maHD);
        List<Object[]> listCT = hdDao.getThongTinChiTiet(maHD);
        for (Object[] row : listCT) {
            if (row[5].equals("Yêu cầu hủy") && XAuth.isManager()) {
                lblHuy.setVisible(true);
                lblNoiDungHuy.setVisible(true);
                btnTuChoiHuy.setVisible(true);
                btnXacNhanHuy.setVisible(true);
                String noiDungHuy = (String) row[9];
                lblNoiDungHuy.setText(noiDungHuy);
            } else {
                lblHuy.setVisible(false);
                lblNoiDungHuy.setVisible(false);
                btnTuChoiHuy.setVisible(false);
                btnXacNhanHuy.setVisible(false);
//                String noiDungHuy = (String) row[10];
                lblNoiDungHuy.setText("");
            }
            lblMaHD.setText((String) row[0]);
            lblNguoiTao.setText((String) row[1]);
            String TimeTao = String.valueOf(row[2]);
            lblThoiGianTao.setText(TimeTao);
            String TimeTT = String.valueOf(row[3]);
            lblThoiGianThanhToan.setText(TimeTT);
            lblGhiChu.setText((String) row[4]);
            lblTrangThai.setText((String) row[5]);
            String tienSP = String.valueOf(row[6]);
            lblTienSP.setText(String.format("%,.0f", row[6]));
            double cpk = (double) row[7] * 1000;
            lblPhiKhac.setText(String.valueOf(String.format("%,.0f", cpk)));
            String tt = String.valueOf(row[8]);
            lblTongTien.setText(String.format("%,.0f", row[8]));
            String gt = String.valueOf(row[10]);
            if (gt.equals("null")) {
                lblGiaTriVouCher.setText("Không có");
            } else {
                lblGiaTriVouCher.setText(gt);
            }

        }
    }

    public void fillTableLSHoaDonCT() {
        String maHD = (String) tblLSHoaDon.getValueAt(row1, 0);
        lblMaHD1.setText(maHD);
        List<Object[]> listCT = hdDao.getThongTinChiTiet(maHD);
        for (Object[] row : listCT) {
            lblMaHD1.setText((String) row[0]);
            lblNguoiTao1.setText((String) row[1]);
            //   lblKhuyenMai1.setText((String) row[2]);
            String TimeTao = String.valueOf(row[2]);
            lblThoiGianTao1.setText(TimeTao);
            String TimeTT = String.valueOf(row[3]);
            lblThoiGianTT1.setText(TimeTT);
            lblGhiChu1.setText((String) row[4]);
            lblTrangThai1.setText((String) row[5]);
            String tienSP = String.valueOf(row[6]);
            lblTienSP1.setText(String.format("%,.0f", row[6]));
            double cpk = (double) row[7] * 1000;
            lblPhiKhac1.setText(String.valueOf(String.format("%,.0f", cpk)));
            String tt = String.valueOf(row[8]);
            lblTongTien1.setText(String.format("%,.0f", row[8]));
            String gt = String.valueOf(row[10]);
            if (gt.equals("null")) {
                lblGiaTriVoucher1.setText("Không có");
            } else {
                lblGiaTriVoucher1.setText(gt);
            }
        }
    }

    public void Reset() {
        lblMaHD.setText("");
        lblNguoiTao.setText("");
        lblKhuyenMai.setText("");
        String TimeTao = "";
        lblThoiGianTao.setText(TimeTao);
        String TimeTT = "";
        lblThoiGianThanhToan.setText(TimeTT);
        lblGhiChu.setText("");
        lblTrangThai.setText("");
        lblTienSP.setText("");
        String cpk = "";
        lblPhiKhac.setText(cpk);
        String tt = "";
        lblTongTien.setText(tt);
        lblGiaTriVouCher.setText("");
    }

    public void Reset2() {
        lblMaHD1.setText("");
        lblNguoiTao1.setText("");
        String TimeTao = "";
        lblThoiGianTao1.setText(TimeTao);
        String TimeTT = "";
        lblThoiGianTT1.setText(TimeTT);
        lblGhiChu1.setText("");
        lblTrangThai1.setText("");
        lblTienSP1.setText("");
        String cpk = "";
        lblPhiKhac1.setText(cpk);
        String tt = "";
        lblTongTien1.setText(tt);
        lblGiaTriVoucher1.setText("");
    }

    public void updateHoaDon() {
        row = tblHoaDon.getSelectedRow();
        String maHD = (String) tblHoaDon.getValueAt(row, 0);
        hdDao.update(maHD);
        statuses.clear();
        fillTableHoaDon();
        row = -1;
        fillTableHoaDonCT();
        fillTableLSHoaDon();

    }

    public void updateHuyHoaDon() {
        int row2 = -1;
        String ma = "";
        try {
            row2 = tblHoaDon.getSelectedRow();
        } catch (Exception e) {
        }

        ma = tblHoaDon.getValueAt(row2, 0).toString();
        hdDao.updateTrangThai(ma);
        hdDao.updateLyDo(userInput, ma);
        statuses.clear();
        Reset();
        fillTableHoaDon();
        row = -1;
        fillTableHoaDonCT();
    }

    public void updateTrangThaiHuy() {
        int row2 = -1;
        String ma = "";
        try {
            row2 = tblHoaDon.getSelectedRow();
        } catch (Exception e) {
        }

        ma = tblHoaDon.getValueAt(row2, 0).toString();
        hdDao.updateTrangThai_KhoiPhuc(ma);
        hdDao.updateLyDo("", ma);
        statuses.clear();
        Reset();
        loadVisible();
        fillTableHoaDon();
        row = -1;
        fillTableHoaDonCT();
        JOptionPane.showMessageDialog(null, "Đã từ chối hủy hóa đơn");
    }

    public void updateXacNhanHuy() {
        int row2 = -1;
        String ma = "";
        try {
            row2 = tblHoaDon.getSelectedRow();
        } catch (Exception e) {
        }

        ma = tblHoaDon.getValueAt(row2, 0).toString();
        hdDao.updateTrangThaiHuyHoaDon(ma);
//        hdDao.updateLyDo(userInput, ma);
        Reset();
        statuses.clear();
        loadVisible();
        fillTableHoaDon();
        row = -1;
        fillTableHoaDonCT();
        fillTableLSHoaDon();
        JOptionPane.showMessageDialog(null, "Đã xác nhận hủy hóa đơn");
    }

    public void xemLyDo() {

        String maHDHuy;
        int rowMaHDHuy;
        rowMaHDHuy = tblLSHoaDon.getSelectedRow();
        maHDHuy = tblLSHoaDon.getValueAt(rowMaHDHuy, 0).toString();
        List<Object[]> lhd = hdDao.getHoaDonMenu(maHDHuy);
        for (Object[] objects : lhd) {
            if (objects[8].toString().equals("Đã hủy")) {
                if (objects[11] != null) {
                    lblLyDo.setVisible(true);
                    lbllLyDoHuy.setVisible(true);
                    lbllLyDoHuy.setText(objects[11].toString());
                }
            } else {
                lblLyDo.setVisible(false);
                lbllLyDoHuy.setVisible(false);
            }
        }
    }

    public void loadVisible() {
        lblHuy.setVisible(false);
        lblNoiDungHuy.setVisible(false);
        btnTuChoiHuy.setVisible(false);
        btnXacNhanHuy.setVisible(false);
    }

    public void fillHDTheoNgay(String date) {
        DefaultTableModel model = (DefaultTableModel) tblLSHoaDon.getModel();
        model.setRowCount(0);
        List<Object[]> list = hdDao.loadHDTheoNgay(date);
        for (Object[] row : list) {
            model.addRow(new Object[]{row[0], row[1], row[2], row[3], row[4], row[5]});
        }
    }

    class CustomRowRenderer implements TableCellRenderer {

        private final List<String> statuses;
        private final DefaultTableCellRenderer defaultRenderer = new DefaultTableCellRenderer();

        public CustomRowRenderer(List<String> statuses) {
            this.statuses = statuses;
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = defaultRenderer.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            // Đặt màu cho chữ dựa trên trạng thái
            String status = statuses.get(row);
            if ("Đang xử lý".equals(status)) {
                c.setForeground(Color.BLACK);
            } else if ("Yêu cầu hủy".equals(status)) {
                c.setForeground(Color.RED);
            }
            return c;
        }
    }

}
